name: Build Yuki OS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib

      - name: Build OS
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yuki-os-floppy
          path: os.flp
