name: Build OS Image with GRUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up NASM
        run: sudo apt-get install -y nasm

      - name: Set up GCC (32-bit)
        run: sudo apt-get install -y gcc-multilib

      - name: Set up GRUB
        run: sudo apt-get install -y grub2-common xorriso

      - name: Build kernel
        run: |
          nasm -f elf -o start.o start.asm
          gcc -m32 -ffreestanding -c kernel.c -o kernel.o
          ld -m elf_i386 -Ttext 0x1000 -o kernel.bin start.o kernel.o

      - name: Prepare ISO directory
        run: |
          mkdir -p isodir/boot/grub
          cp kernel.bin isodir/boot/kernel.bin
          cp grub.cfg isodir/boot/grub/grub.cfg

      - name: Create ISO image
        run: grub-mkrescue -o yuki-os.iso isodir

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: yuki-os-iso
          path: yuki-os.iso
