# .github/workflows/build.yml

name: Build Yuki OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib make

      - name: Build OS
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yuki-os.flp
          path: yuki-os.flp
